#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-setuptools_git_ls_files
Version  : 0.1.2
Release  : 5
URL      : https://files.pythonhosted.org/packages/53/53/868cb0beb7841f257c7b2b7745226d4809c2a821d3ce6d281bd7bc305c72/setuptools_git_ls_files-0.1.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/53/53/868cb0beb7841f257c7b2b7745226d4809c2a821d3ce6d281bd7bc305c72/setuptools_git_ls_files-0.1.2.tar.gz
Summary  : Use git to list all files, including submodules
Group    : Development/Tools
License  : MIT
Requires: pypi-setuptools_git_ls_files-license = %{version}-%{release}
Requires: pypi-setuptools_git_ls_files-python = %{version}-%{release}
Requires: pypi-setuptools_git_ls_files-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(setuptools_scm)

%description
A plugin for setuptools that finds all git tracked files, including submodules.
        The command used is `git ls-files --cached --recurse-submodule`.

%package license
Summary: license components for the pypi-setuptools_git_ls_files package.
Group: Default

%description license
license components for the pypi-setuptools_git_ls_files package.


%package python
Summary: python components for the pypi-setuptools_git_ls_files package.
Group: Default
Requires: pypi-setuptools_git_ls_files-python3 = %{version}-%{release}

%description python
python components for the pypi-setuptools_git_ls_files package.


%package python3
Summary: python3 components for the pypi-setuptools_git_ls_files package.
Group: Default
Requires: python3-core
Provides: pypi(setuptools_git_ls_files)

%description python3
python3 components for the pypi-setuptools_git_ls_files package.


%prep
%setup -q -n setuptools_git_ls_files-0.1.2
cd %{_builddir}/setuptools_git_ls_files-0.1.2
pushd ..
cp -a setuptools_git_ls_files-0.1.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656407347
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-setuptools_git_ls_files
cp %{_builddir}/setuptools_git_ls_files-0.1.2/LICENSE %{buildroot}/usr/share/package-licenses/pypi-setuptools_git_ls_files/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-setuptools_git_ls_files/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
